[project]
name = "car"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "django>=5.2.8",
    "pillow>=12.0.0",
    "python-decouple>=3.8",
    "requests>=2.32.5",
]
